# Creation of file
# Project Name

Temporary description

## Table of Contents

Filler table of contents

## Introduction

Website about me

## Features

Features

- [ ] Feature 1
- [ ] Feature 2
- [ ] ...

## Getting Started

Filler guide

### Prerequisites

List any software, tools, or dependencies that users need to have installed before they can use your project.

### Installation

Provide a step-by-step guide on how to install your project. This could include commands to clone the repository, install dependencies, and any other setup tasks.

git clone https://github.com/jwirth1/jwirth1.github.io.git
cd jwirth1.github.io
npm install
